const fs = require('fs');

let content = fs.readFileSync('src/App.tsx', 'utf8');

const translations = [
  ['Meine Fächer', 'My Courses'],
  ['Lade Fächer...', 'Loading courses...'],
  ['Noch keine Fächer angelegt.', 'No courses created yet.'],
  ['Möchtest du das Fach', 'Do you really want to delete course'],
  ['wirklich löschen?', '?'],
  ['Fach löschen', 'Delete course'],
  ['Fachname...', 'Course name...'],
  ['Speichern', 'Save'],
  ['Abbrechen', 'Cancel'],
  ['Neues Fach anlegen', 'Create new course'],
  ['Erneut versuchen', 'Try again'],
  ['Willkommen bei University Acer!', 'Welcome to University Acer!'],
  ['Wähle ein Fach aus der Seitenleiste oder lege ein neues an, um mit deiner Vorbereitung zu starten.', 'Select a course from the sidebar or create a new one to start your preparation.'],
  ['Klicke zum Öffnen', 'Click to open'],
  ['Wissensdatenbank', 'Knowledge Base'],
  ['Klausur-Generator', 'Exam Generator'],
  ['Korrektur & Feedback', 'Correction & Feedback'],
  ['Dokumente und Lehrmaterial', 'Documents and Learning Material'],
  ['Hier kannst du die hochgeladenen Dokumente für dieses Fach einsehen und verwalten.', 'Here you can view and manage uploaded documents for this course.'],
  ['Lade PDEs hoch, damit die KI', 'Upload PDFs so the AI can learn your material.'],
  ['Datei hochladen', 'Upload file'],
  ['Wird hochgeladen...', 'Uploading...'],
  ['Fehler beim Löschen des Dokuments', 'Error deleting document'],
  ['Fehler beim Upload', 'Upload error'],
  ['Verarbeitete Dokumente', 'Processed Documents'],
  ['Keine Dokumente hochgeladen', 'No documents uploaded'],
  ['Dokument löschen', 'Delete document'],
  ['Erstelle eine individuelle Übungsklausur basierend auf deiner Wissensdatenbank.', 'Create a custom practice exam based on your knowledge base.'],
  ['Klausur als PDF generieren', 'Generate Exam as PDF'],
  ['Generiere Klausur...', 'Generating exam...'],
  ['Worüber möchtest du eine Klausur schreiben?', 'What should the exam cover?'],
  ['z.B. 3 Aufgaben zu Matrizen, 2 Aufgaben zu Vektorräumen...', 'e.g., 3 tasks on matrices, 2 tasks on vector spaces...'],
  ['Dateiname (Optional)', 'File Name (Optional)'],
  ['Generierung fehlgeschlagen', 'Generation failed'],
  ['Generierte Klausuren', 'Generated Exams'],
  ['Klausur #', 'Exam #'],
  ['Unbekanntes Datum', 'Unknown Date'],
  ['Wird erstellt...', 'Generating...'],
  ['Wird generiert', 'Generating'],
  ['Fertig', 'Ready'],
  ['Ausstehend', 'Pending'],
  ['PDF herunterladen', 'Download PDF'],
  ['Lade deine bearbeitete Klausur hoch, um eine automatische KI-Bewertung zu erhalten.', 'Upload your solved exam to get an automatic AI evaluation.'],
  ['Welche Klausur hast du bearbeitet?', 'Which exam did you solve?'],
  ['Keine Klausuren vorhanden. Generiere zuerst eine im Klausur-Generator Tab.', 'No exams available. Generate one in the Exam Generator tab first.'],
  ['Klausur auswählen...', 'Select exam...'],
  ['Klausur-PDF ansehen / herunterladen', 'View / Download Exam PDF'],
  ['Klausur-PDF ansehen', 'View Exam PDF'],
  ['Bild oder PDF auswählen', 'Select Image or PDF'],
  ['Scans deiner Handschrift werden unterstützt', 'Scans of your handwriting are supported'],
  ['Durchsuchen', 'Browse'],
  ['Ergebnis hochladen & KI-Feedback erhalten', 'Upload Result & Get AI Feedback'],
  ['Analysiere Antworten...', 'Analyzing answers...'],
  ['Feedback konnte nicht geladen werden', 'Could not load feedback'],
  ['Wähle eine generierte Klausur aus, um deine Lösung hochzuladen und eine Bewertung zu erhalten.', 'Select a generated exam to upload your solution and receive feedback.'],
  ['Zurück zur Übersicht', 'Back to Overview'],
  ['Generiert am', 'Generated on'],
  ['Unbekannt', 'Unknown'],
  ['Hallo! Ich bin bereit, deine Lösung für', 'Hello! I am ready to grade your solution for'],
  ['zu korrigieren.', ' '],
  ['Bitte lade ein PDF oder ein Foto deiner Bearbeitung hoch.', 'Please upload a PDF or photo of your work.'],
  ['Analysiere deine Lösung... Bitte habe einen Moment Geduld.', 'Analyzing your solution... Please wait a moment.'],
  ['Datei hochgeladen', 'File uploaded'],
  ['Keine Datei ausgewählt...', 'No file selected...'],
  ['Senden', 'Send'],
  ['Klausur-Ergebnis', 'Exam Result'],
  ['Punkte', 'Points'],
  ['Bestanden', 'Passed'],
  ['Feedback pro Aufgabe', 'Feedback per Task'],
  ['Stärken', 'Strengths'],
  ['Schwächen laut Skript', 'Weaknesses based on script'],
  ['Flashcards-Trainer', 'Flashcards Trainer'],
  ['Trainiere dein Wissen interaktiv mit KI-generierten Karteikarten basierend auf deinen Materialien.', 'Train your knowledge interactively with AI-generated flashcards.'],
  ['Bereit für dein Karteikarten-Training?', 'Ready for your flashcards training?'],
  ['Lass unsere KI aus deinen Altklausuren und Wissenstabs die wichtigsten Lernfragen für dich als Flashcards extrahieren.', 'Let our AI extract the most important questions from your old exams for you.'],
  ['Flashcards generieren', 'Generate Flashcards'],
  ['KI analysiert Dokumente...', 'AI is analyzing documents...'],
  ['Frage', 'Question'],
  ['Antwort', 'Answer'],
  ['Zum Umdrehen klicken', 'Click to flip'],
  ['Vorherige', 'Previous'],
  ['Karte', 'Card'],
  ['von', 'of'],
  ['Nächste', 'Next'],
  ['In Anki / RemNote importieren (CSV Download)', 'Import into Anki / RemNote (CSV Download)'],
  ['Fehler:', 'Error:'],
  ['Upload fehlgeschlagen', 'Upload failed'],
  ['Wird verarbeitet', 'Processing'],
  ['Lade hier deine Lernmaterialien hoch. Die KI verarbeitet diese automatisch als Grundlage für deine Klausuren.', 'Upload your learning materials here. The AI processes them automatically as a basis for your exams.'],
  ['PDFs (Skripte, Altklausuren) hier ablegen', 'Drop PDFs (transcripts, past exams) here'],
  ['uploadStatus.startsWith(\'Fehler\')', 'uploadStatus.startsWith(\'Error\')'],
  ['Hochgeladene Dateien', 'Uploaded Files'],
  ['Noch keine Dateien hochgeladen.', 'No files uploaded yet.'],
  ['Erstelle eine individuelle Übungsklausur basierend auf deiner Knowledge Base.', 'Create a custom practice exam based on your knowledge base.'],
  ['Keine Klausuren vorhanden. Generiere zuerst eine im Exam Generator Tab.', 'No exams available. Generate one in the Exam Generator tab first.'],
  ['Fach konnte nicht erstellt werden', 'Could not create course'],
  ['Fach konnte nicht gelöscht werden', 'Could not delete course']
];

for (const [de, en] of translations) {
  content = content.split(de).join(en);
}

fs.writeFileSync('src/App.tsx', content);
